package rules;

import com.librarian.model.*;
import java.util.*;

rule "Test"
agenda-group "recommended"
salience 10
    when
        $br: BookRank(rating > 30)
    then
        System.out.println($br.getBook().getTitle());
end

//rule "Print top books"
////agenda-group "recommended"
//no-loop
//salience 3
//    when
//        $maxRating : Number(intValue : intValue) from accumulate(
//            BookRank($rating : rating),
//            max($rating)
//        )
//        //$bestBooks : List() from accumulate(
//        //    BookRank(rating == $maxRating, $bookRank : this),
//        //    collectList($bookRank)
//        //)
//    then
//        System.out.println($maxRating);
//        //printBooks($bestBooks);
//end

//function printBooks(List bestBooks) {
//    for (Object bookRank: bestBooks) {
//        BookRank br = (BookRank) bookRank;
//        Book book = br.getBook();
//        System.out.println("KEY: " + book.getKey());
//        System.out.println("TITLE: " + book.getTitle());
//        //System.out.println("AUTHOR: " + book.getAuthors()[0].getName());
//    }
//}

// GO TO ANOTHER
// AGENDA GROUP PLS

rule "Remove book ranks"
agenda-group "cleanup"
salience 2
    when
        Flag($up: rp.up)
        $br: BookRank(userPreferences == $up)
    then
        delete($br);
end

rule "Remove adult flag"
agenda-group "cleanup"
salience 1
no-loop
    when
        $f: Flag(name == "flag_adult", $rp: rp)
    then
        delete($rp);
        delete($f);
end

rule "Remove young adult flag"
agenda-group "cleanup"
salience 1
no-loop
    when
        $f: Flag(name == "flag_ya", $rp: rp)
    then
        delete($rp);
        delete($f);
end

rule "Remove juvenile flag"
agenda-group "cleanup"
salience 1
no-loop
    when
        $f: Flag(name == "flag_juvenile", $rp: rp)
    then
        delete($rp);
        delete($f);
end

rule "Remove recommending user preference"
agenda-group "cleanup"
salience 1
no-loop
    when
        $rp: RecommendingPreferences()
    then
        delete($rp);
end

rule "Remove recommending book from singleBook"
agenda-group "cleanup2"
salience 1
no-loop
    when
        $rb: RecommendingBook()
    then
        delete($rb);
end

rule "Remove recommending bookranks from singleBook"
agenda-group "cleanup2"
salience 1
no-loop
    when
        $br: BookRank()
    then
        delete($br);
end