package rules;

import com.librarian.model.*;
import java.util.List;
import java.util.Set;

rule "Delete already read books"
no-loop
salience 96
    when
        $rp: RecommendingPreferences($list: up.readBooks, $up: up)
        $br: BookRank(userPreferences == $up, $id: book.id)
        eval(hasReadBook($list, $id))
    then
        delete($br);
end

function Boolean hasReadBook(Set readBooks, Long id) {
    for (Object book: readBooks) {
        ReadBook rb = (ReadBook) book;
        if (rb.getBook().getId().equals(id)) {
            return true;
        }
    }
    return false;
}