package rules;

import com.librarian.model.*;
import java.util.List;

rule "Target year rule"
no-loop
salience 90
    when
        $up: UserPreferences($ty: targetYear)
        $br: BookRank(userPreferences== $up, progress==1, $bty: book.firstPublishedYear)
        eval(isTargetYear($ty, $bty))
    then
        Integer rank = $br.getRating();
        modify($br){ setRating(rank + 10), setProgress(2) }
end

rule "Target year -1 rule"
no-loop
salience 90
    when
        $up: UserPreferences($ty: targetYear)
        $br: BookRank(userPreferences == $up, progress==1, book.firstPublishedYear == -1)
    then
        Integer rank = $br.getRating();
        modify($br){ setRating(rank + 3), setProgress(2) }
end

function Boolean isTargetYear(ETargetYear ety, Integer bty) {
    Integer ty = ety.ordinal();
    if (bty == -1) {
        return false;
    } else if (ty == 0) {
        return bty <= 2000;
    } else if (ty == 1) {
        return bty >= 2000 && bty <= 2015;
    }  else {
        return bty > 2015;
    }
}