package librarianBase;

import com.librarian.model.*;

declare Flag
    name : String
    up : UserPreferences
end

// AGE RULES

//rule "Adult"
//salience 100
//no-loop
//    when
//        $u: UserPreferences(age > 22)
//        not Flag(name == "flag_adult", up == $u)
//        not Flag(name == "flag_juvenile", up == $u)
//        not Flag(name == "flag_ya", up == $u)
//    then
//        insert(new Flag("flag_adult", $u));
//end
//
//rule "Young adult"
//salience 100
//no-loop
//    when
//        $u: UserPreferences(age > 12)
//        not Flag(name == "flag_ya", up == $u)
//    then
//        insert(new Flag("flag_ya", $u));
//end
//
//rule "Juvenile"
//salience 100
//no-loop
//    when
//        $u: UserPreferences(age > 2)
//        not Flag(name == "flag_juvenile", up == $u)
//    then
//        insert(new Flag("flag_juvenile", $u));
//end

rule "Filter juvenile books"
salience 99
    when
        Flag(name == "flag_juvenile", $up: up)
        not Flag(name == "flag_adult", up == $up)
        not Flag(name == "flag_ya", up == $up)
        $b: Book(age == EAge.JUVENILE)
    then
        BookRank $bookRank = new BookRank();
        $bookRank.setBook($b);
        $bookRank.setRating(0);
        $bookRank.setUserPreferences($up);
        insert($bookRank);
end

rule "Filter young adult books"
salience 99
    when
        Flag(name == "flag_ya", $up: up)
        Flag(name == "flag_juvenile", up == $up)
        not Flag(name == "flag_adult", up == $up)
        $b: Book(age == EAge.YOUNG_ADULT)
    then
        BookRank $bookRank = new BookRank();
        $bookRank.setBook($b);
        $bookRank.setRating(0);
        $bookRank.setUserPreferences($up);
        insert($bookRank);
end

rule "Filter adult books"
salience 99
    when
        Flag(name == "flag_adult", $up: up)
        Flag(name == "flag_ya", up == $up)
        Flag(name == "flag_juvenile", up == $up)
        $b: Book()
    then
        BookRank $bookRank = new BookRank();
        $bookRank.setBook($b);
        $bookRank.setRating(0);
        $bookRank.setUserPreferences($up);
        insert($bookRank);
end

// CLEAN UP

rule "Remove book ranks"
salience 2
    when
        Flag($up: up)
        $br: BookRank(userPreferences == $up)
    then
        delete($br);
end

rule "Remove juvenile flag"
salience 1
no-loop
    when
        $f: Flag(name == "flag_juvenile", $up: up)
    then
        delete($up);
        delete($f);
end